//! Embedded wwPDB Chemical Component Dictionary (heavy atoms and bonds).
//!
//! The table is generated by `scripts/export_ccd.py` and decompressed on first use. Only the
//! byte offset of each component is indexed; components are decoded when requested.

use std::{collections::HashMap, sync::OnceLock};

use super::{BondOrder, Element};

static COMPRESSED: &[u8] = include_bytes!("../../data/ccd/components.bin.zst");

/// Polymer class of a chemical component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ComponentKind {
    Other,
    Peptide,
    Dna,
    Rna,
    Saccharide,
    NonPolymer,
}

impl ComponentKind {
    fn from_code(code: u8) -> Self {
        match code {
            1 => Self::Peptide,
            2 => Self::Dna,
            3 => Self::Rna,
            4 => Self::Saccharide,
            5 => Self::NonPolymer,
            _ => Self::Other,
        }
    }

    pub const fn is_amino_acid(self) -> bool {
        matches!(self, Self::Peptide)
    }

    pub const fn is_nucleotide(self) -> bool {
        matches!(self, Self::Dna | Self::Rna)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ComponentAtom {
    pub name: String,
    pub element: Element,
    pub formal_charge: i8,
    pub aromatic: bool,
    pub leaving: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ComponentBond {
    pub a: usize,
    pub b: usize,
    pub order: BondOrder,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Component {
    pub id: String,
    pub kind: ComponentKind,
    /// Standard parent of a modified residue, for example `MET` for `MSE`.
    pub parent: Option<String>,
    pub one_letter_code: Option<char>,
    pub atoms: Vec<ComponentAtom>,
    pub bonds: Vec<ComponentBond>,
}

impl Component {
    pub fn atom_index(&self, name: &str) -> Option<usize> {
        self.atoms.iter().position(|atom| atom.name == name)
    }
}

struct Dictionary {
    data: Vec<u8>,
    offsets: HashMap<String, usize>,
}

fn dictionary() -> Option<&'static Dictionary> {
    static DICTIONARY: OnceLock<Option<Dictionary>> = OnceLock::new();
    DICTIONARY
        .get_or_init(|| {
            let data = match zstd::decode_all(COMPRESSED) {
                Ok(data) => data,
                Err(error) => {
                    log::error!("could not decompress the chemical component dictionary: {error}");
                    return None;
                }
            };
            let offsets = match index(&data) {
                Some(offsets) => offsets,
                None => {
                    log::error!("the embedded chemical component dictionary is malformed");
                    return None;
                }
            };
            Some(Dictionary { data, offsets })
        })
        .as_ref()
}

struct Reader<'a> {
    data: &'a [u8],
    cursor: usize,
}

impl<'a> Reader<'a> {
    fn u8(&mut self) -> Option<u8> {
        let value = *self.data.get(self.cursor)?;
        self.cursor += 1;
        Some(value)
    }

    fn u16(&mut self) -> Option<u16> {
        let bytes = self.data.get(self.cursor..self.cursor + 2)?;
        self.cursor += 2;
        Some(u16::from_le_bytes([bytes[0], bytes[1]]))
    }

    fn u32(&mut self) -> Option<u32> {
        let bytes = self.data.get(self.cursor..self.cursor + 4)?;
        self.cursor += 4;
        Some(u32::from_le_bytes(bytes.try_into().ok()?))
    }

    fn str(&mut self) -> Option<&'a str> {
        let length = usize::from(self.u8()?);
        let bytes = self.data.get(self.cursor..self.cursor + length)?;
        self.cursor += length;
        std::str::from_utf8(bytes).ok()
    }

    fn skip_component(&mut self) -> Option<()> {
        self.str()?;
        self.u8()?;
        self.str()?;
        self.u8()?;
        let atoms = self.u16()?;
        for _ in 0..atoms {
            self.str()?;
            self.str()?;
            self.cursor += 2;
        }
        let bonds = usize::from(self.u16()?);
        self.cursor += bonds * 5;
        (self.cursor <= self.data.len()).then_some(())
    }
}

fn index(data: &[u8]) -> Option<HashMap<String, usize>> {
    if data.get(..4)? != b"ACCD" {
        return None;
    }
    let mut reader = Reader { data, cursor: 4 };
    if reader.u32()? != 1 {
        return None;
    }
    let count = reader.u32()? as usize;
    let mut offsets = HashMap::with_capacity(count);
    for _ in 0..count {
        let offset = reader.cursor;
        let id = reader.str()?.to_string();
        reader.cursor = offset;
        reader.skip_component()?;
        offsets.insert(id, offset);
    }
    Some(offsets)
}

fn decode(data: &[u8], offset: usize) -> Option<Component> {
    let mut reader = Reader {
        data,
        cursor: offset,
    };
    let id = reader.str()?.to_string();
    let kind = ComponentKind::from_code(reader.u8()?);
    let parent = Some(reader.str()?.to_string()).filter(|value| !value.is_empty());
    let code = reader.u8()?;
    let one_letter_code = (code != 0).then_some(char::from(code));
    let atom_count = usize::from(reader.u16()?);
    let mut atoms = Vec::with_capacity(atom_count);
    for _ in 0..atom_count {
        let name = reader.str()?.to_string();
        let element = reader.str()?.parse().unwrap_or(Element::Unknown);
        let formal_charge = reader.u8()? as i8;
        let flags = reader.u8()?;
        atoms.push(ComponentAtom {
            name,
            element,
            formal_charge,
            aromatic: flags & 1 != 0,
            leaving: flags & 2 != 0,
        });
    }
    let bond_count = usize::from(reader.u16()?);
    let mut bonds = Vec::with_capacity(bond_count);
    for _ in 0..bond_count {
        let a = usize::from(reader.u16()?);
        let b = usize::from(reader.u16()?);
        let code = reader.u8()?;
        if a >= atom_count || b >= atom_count {
            return None;
        }
        let order = if code & 0x10 != 0 {
            BondOrder::Aromatic
        } else {
            BondOrder::from_code(code & 0x0f).unwrap_or(BondOrder::Single)
        };
        bonds.push(ComponentBond { a, b, order });
    }
    Some(Component {
        id,
        kind,
        parent,
        one_letter_code,
        atoms,
        bonds,
    })
}

/// Looks up a component by its three-to-five character identifier (case-insensitive).
pub fn component(id: &str) -> Option<Component> {
    let dictionary = dictionary()?;
    let offset = dictionary
        .offsets
        .get(id)
        .or_else(|| dictionary.offsets.get(&id.to_ascii_uppercase()))?;
    decode(&dictionary.data, *offset)
}

/// Caches decoded components for one structure, since residues repeat.
#[derive(Default)]
pub struct ComponentCache {
    components: HashMap<String, Option<std::sync::Arc<Component>>>,
}

impl ComponentCache {
    pub fn get(&mut self, id: &str) -> Option<std::sync::Arc<Component>> {
        if let Some(cached) = self.components.get(id) {
            return cached.clone();
        }
        let value = component(id).map(std::sync::Arc::new);
        self.components.insert(id.to_string(), value.clone());
        value
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_standard_and_ligand_components() {
        let phe = component("PHE").unwrap();
        assert_eq!(phe.kind, ComponentKind::Peptide);
        assert_eq!(phe.one_letter_code, Some('F'));
        assert!(phe.atoms.iter().all(|atom| atom.element != Element::H));
        let cg = phe.atom_index("CG").unwrap();
        let cd1 = phe.atom_index("CD1").unwrap();
        let ring = phe
            .bonds
            .iter()
            .find(|bond| (bond.a == cg && bond.b == cd1) || (bond.a == cd1 && bond.b == cg))
            .unwrap();
        assert_eq!(ring.order, BondOrder::Aromatic);
        let c = phe.atom_index("C").unwrap();
        let o = phe.atom_index("O").unwrap();
        assert!(phe.bonds.iter().any(|bond| {
            ((bond.a == c && bond.b == o) || (bond.a == o && bond.b == c))
                && bond.order == BondOrder::Double
        }));
        assert!(phe.atoms[phe.atom_index("OXT").unwrap()].leaving);

        let mse = component("mse").unwrap();
        assert_eq!(mse.parent.as_deref(), Some("MET"));
        assert_eq!(component("DA").unwrap().kind, ComponentKind::Dna);
        let heme = component("HEM").unwrap();
        assert!(heme.atoms.iter().any(|atom| atom.element == Element::Fe));
        assert!(component("NOT_A_COMPONENT").is_none());
    }
}
